import type { Rank, ServerType } from '../data';
import { getDefaultPermissionsForRank } from '../data';

// Permission plugin types
export type PermissionPluginType = 'luckperms' | 'groupmanager' | 'permissionsex' | 'ultrapermissions' | 'powerfulperms';

export interface GenerateOptions {
  serverType: ServerType;
  selectedPlugins: string[];
  ranks: Rank[];
  permissionPlugin?: PermissionPluginType;
}

// Get the selected permission plugin from the selected plugins list
export function getSelectedPermissionPlugin(selectedPlugins: string[]): PermissionPluginType {
  if (selectedPlugins.includes('luckperms')) return 'luckperms';
  if (selectedPlugins.includes('groupmanager')) return 'groupmanager';
  if (selectedPlugins.includes('permissionsex')) return 'permissionsex';
  if (selectedPlugins.includes('ultrapermissions')) return 'ultrapermissions';
  if (selectedPlugins.includes('powerfulperms')) return 'powerfulperms';
  return 'luckperms'; // Default fallback
}

// Plugin info for display
export const permissionPluginInfo: Record<PermissionPluginType, { name: string; configPath: string; syncCommand: string }> = {
  luckperms: {
    name: 'LuckPerms',
    configPath: '/plugins/LuckPerms/',
    syncCommand: '/lp sync',
  },
  groupmanager: {
    name: 'GroupManager',
    configPath: '/plugins/GroupManager/worlds/<worldname>/',
    syncCommand: '/manload',
  },
  permissionsex: {
    name: 'PermissionsEx',
    configPath: '/plugins/PermissionsEx/',
    syncCommand: '/pex reload',
  },
  ultrapermissions: {
    name: 'UltraPermissions',
    configPath: '/plugins/UltraPermissions/',
    syncCommand: '/upc reload',
  },
  powerfulperms: {
    name: 'PowerfulPerms',
    configPath: '/plugins/PowerfulPerms/',
    syncCommand: '/pp reload',
  },
};

export function generateYaml(options: GenerateOptions): string {
  const plugin = options.permissionPlugin || getSelectedPermissionPlugin(options.selectedPlugins);

  switch (plugin) {
    case 'groupmanager':
      return generateGroupManagerYaml(options);
    case 'permissionsex':
      return generatePermissionsExYaml(options);
    case 'ultrapermissions':
      return generateUltraPermissionsYaml(options);
    case 'powerfulperms':
      return generatePowerfulPermsYaml(options);
    default:
      return generateLuckPermsYaml(options);
  }
}

export function generateCommands(options: GenerateOptions): string {
  const plugin = options.permissionPlugin || getSelectedPermissionPlugin(options.selectedPlugins);

  switch (plugin) {
    case 'groupmanager':
      return generateGroupManagerCommands(options);
    case 'permissionsex':
      return generatePermissionsExCommands(options);
    case 'ultrapermissions':
      return generateUltraPermissionsCommands(options);
    case 'powerfulperms':
      return generatePowerfulPermsCommands(options);
    default:
      return generateLuckPermsCommands(options);
  }
}

// ==================== LUCKPERMS ====================

function generateLuckPermsYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Permission Plugin: LuckPerms`);
  lines.push('');
  lines.push('groups:');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    lines.push(`  ${rank.name}:`);

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    if (rankIndex > 0) {
      const parentRank = ranks[rankIndex - 1];
      lines.push('    inheritance:');
      lines.push(`      - ${parentRank.name}`);
    }

    if (rankSpecificPerms.length > 0) {
      lines.push('    permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`      - ${perm.node}`);
      }
    }

    lines.push('    meta:');
    lines.push(`      prefix: '${rank.prefixColor}${rank.prefix}'`);
    if (rank.separator && rank.separator !== ':') {
      lines.push(`      separator: '${rank.separator}'`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateLuckPermsCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# PERMSTACK - LUCKPERMS SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('# Create groups (lowest to highest)');
  for (const rank of ranks) {
    lines.push(`/lp creategroup ${rank.name}`);
  }
  lines.push('');

  lines.push('# Set inheritance chain');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/lp group ${rank.name} parent add ${parent.name}`);
  }
  lines.push('');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/lp group ${rank.name} permission set ${perm.node} true`);
      }
      lines.push('');
    }
  }

  const baseWeight = 79;
  lines.push('# ---------- WEIGHTS ----------');
  for (let i = 0; i < ranks.length; i++) {
    const rank = ranks[i];
    const weight = baseWeight + i;
    lines.push(`/lp group ${rank.name} setweight ${weight}`);
  }
  lines.push('');

  lines.push('# ---------- PREFIXES ----------');
  for (let i = 0; i < ranks.length; i++) {
    const rank = ranks[i];
    const weight = baseWeight + i;
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/lp group ${rank.name} meta setprefix ${weight} "${prefix}"`);
  }

  return lines.join('\n');
}

// ==================== GROUPMANAGER ====================

function generateGroupManagerYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Permission Plugin: GroupManager`);
  lines.push('# Place this file at: /plugins/GroupManager/worlds/<worldname>/groups.yml');
  lines.push('');
  lines.push('groups:');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    lines.push(`  ${rank.name}:`);
    lines.push('    default: ' + (rank.name === 'default' || rank.name === 'player' ? 'true' : 'false'));

    if (rankSpecificPerms.length > 0) {
      lines.push('    permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`      - ${perm.node}`);
      }
    } else {
      lines.push('    permissions: []');
    }

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    if (rankIndex > 0) {
      const parentRank = ranks[rankIndex - 1];
      lines.push('    inheritance:');
      lines.push(`      - ${parentRank.name}`);
    } else {
      lines.push('    inheritance: []');
    }

    lines.push('    info:');
    lines.push(`      prefix: '${rank.prefixColor}${rank.prefix}'`);
    lines.push(`      build: true`);
    lines.push('');
  }

  return lines.join('\n');
}

function generateGroupManagerCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# PERMSTACK - GROUPMANAGER SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('# Create groups');
  for (const rank of ranks) {
    lines.push(`/mangadd ${rank.name}`);
  }
  lines.push('');

  lines.push('# Set inheritance');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/mangaddi ${rank.name} ${parent.name}`);
  }
  lines.push('');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/mangaddp ${rank.name} ${perm.node}`);
      }
      lines.push('');
    }
  }

  lines.push('# ---------- PREFIXES ----------');
  for (const rank of ranks) {
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/mangaddv ${rank.name} prefix "${prefix}"`);
  }
  lines.push('');
  lines.push('# Reload GroupManager');
  lines.push('/manload');

  return lines.join('\n');
}

// ==================== PERMISSIONSEX ====================

function generatePermissionsExYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Permission Plugin: PermissionsEx`);
  lines.push('# Place this file at: /plugins/PermissionsEx/permissions.yml');
  lines.push('');
  lines.push('groups:');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    lines.push(`  ${rank.name}:`);
    lines.push('    default: ' + (rank.name === 'default' || rank.name === 'player' ? 'true' : 'false'));

    if (rankSpecificPerms.length > 0) {
      lines.push('    permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`      - ${perm.node}`);
      }
    }

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    if (rankIndex > 0) {
      const parentRank = ranks[rankIndex - 1];
      lines.push('    inheritance:');
      lines.push(`      - ${parentRank.name}`);
    }

    lines.push('    options:');
    lines.push(`      prefix: '${rank.prefixColor}${rank.prefix}'`);
    lines.push(`      rank: ${ranks.length - rankIndex}`);
    lines.push('');
  }

  return lines.join('\n');
}

function generatePermissionsExCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# PERMSTACK - PERMISSIONSEX SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('# Create groups');
  for (const rank of ranks) {
    lines.push(`/pex group ${rank.name} create`);
  }
  lines.push('');

  lines.push('# Set inheritance');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/pex group ${rank.name} parents add ${parent.name}`);
  }
  lines.push('');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/pex group ${rank.name} add ${perm.node}`);
      }
      lines.push('');
    }
  }

  lines.push('# ---------- PREFIXES ----------');
  for (const rank of ranks) {
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/pex group ${rank.name} prefix "${prefix}"`);
  }
  lines.push('');
  lines.push('# Reload PermissionsEx');
  lines.push('/pex reload');

  return lines.join('\n');
}

// ==================== ULTRAPERMISSIONS ====================

function generateUltraPermissionsYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Permission Plugin: UltraPermissions`);
  lines.push('# Note: UltraPermissions uses a GUI-based system.');
  lines.push('# Use the commands below or import via the web editor.');
  lines.push('');
  lines.push('# UltraPermissions stores data in MySQL/SQLite,');
  lines.push('# so manual YAML editing is limited.');
  lines.push('# Use /upc commands instead.');
  lines.push('');

  // Still provide a reference format
  lines.push('# Reference format:');
  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    lines.push(`# ${rank.name}:`);
    if (rankSpecificPerms.length > 0) {
      lines.push('#   permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`#     - ${perm.node}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateUltraPermissionsCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# PERMSTACK - ULTRAPERMISSIONS SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');
  lines.push('# Note: UltraPermissions is GUI-based. You can use');
  lines.push('# /upc or the web editor for easier management.');
  lines.push('');

  lines.push('# Create groups');
  for (const rank of ranks) {
    lines.push(`/upc createGroup ${rank.name}`);
  }
  lines.push('');

  lines.push('# Set inheritance');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/upc group ${rank.name} addInheritance ${parent.name}`);
  }
  lines.push('');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/upc group ${rank.name} addPermission ${perm.node}`);
      }
      lines.push('');
    }
  }

  lines.push('# ---------- PREFIXES ----------');
  for (const rank of ranks) {
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/upc group ${rank.name} setPrefix "${prefix}"`);
  }

  return lines.join('\n');
}

// ==================== POWERFULPERMS ====================

function generatePowerfulPermsYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Permission Plugin: PowerfulPerms`);
  lines.push('# Note: PowerfulPerms uses MySQL for storage.');
  lines.push('# Use the commands below to set up permissions.');
  lines.push('');

  // Provide a reference format
  lines.push('# Reference - Groups and permissions:');
  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    lines.push(`# ${rank.name}:`);
    if (rankSpecificPerms.length > 0) {
      lines.push('#   permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`#     - ${perm.node}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generatePowerfulPermsCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  lines.push('# ==========================================');
  lines.push('# PERMSTACK - POWERFULPERMS SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  lines.push('# Create groups');
  for (const rank of ranks) {
    lines.push(`/pp group ${rank.name} create`);
  }
  lines.push('');

  lines.push('# Set inheritance');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/pp group ${rank.name} setparent ${parent.name}`);
  }
  lines.push('');

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/pp group ${rank.name} add ${perm.node}`);
      }
      lines.push('');
    }
  }

  lines.push('# ---------- PREFIXES ----------');
  for (const rank of ranks) {
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/pp group ${rank.name} setprefix "${prefix}"`);
  }
  lines.push('');
  lines.push('# Reload PowerfulPerms');
  lines.push('/pp reload');

  return lines.join('\n');
}

// ==================== JSON EXPORT ====================

interface LuckPermsNode {
  type: 'permission' | 'inheritance' | 'prefix' | 'suffix' | 'weight' | 'meta' | 'display_name';
  key: string;
  value: boolean;
}

export function generateJson(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks, permissionPlugin } = options;
  const plugin = permissionPlugin || getSelectedPermissionPlugin(selectedPlugins);

  const groups: Record<string, { nodes: LuckPermsNode[] }> = {};
  const baseWeight = 79;

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(rank.level, serverType, selectedPlugins);
    const rankSpecificPerms = permissions.filter((p) => p.recommendedRank === rank.level);

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    const parentRank = rankIndex > 0 ? ranks[rankIndex - 1] : null;
    const weight = baseWeight + rankIndex;

    const nodes: LuckPermsNode[] = [];

    for (const perm of rankSpecificPerms) {
      nodes.push({
        type: 'permission',
        key: perm.node,
        value: true,
      });
    }

    if (parentRank) {
      nodes.push({
        type: 'inheritance',
        key: `group.${parentRank.name}`,
        value: true,
      });
    }

    const prefixValue = `${rank.prefixColor}${rank.prefix}`.trim();
    if (prefixValue) {
      nodes.push({
        type: 'prefix',
        key: `prefix.${weight}.${prefixValue}`,
        value: true,
      });
    }

    nodes.push({
      type: 'weight',
      key: `weight.${weight}`,
      value: true,
    });

    if (rank.separator && rank.separator !== ':') {
      nodes.push({
        type: 'meta',
        key: `meta.separator.${rank.separator}`,
        value: true,
      });
    }

    groups[rank.name] = { nodes };
  }

  const output = {
    metadata: {
      generatedBy: 'PermStack',
      generatedAt: new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC',
      permissionPlugin: plugin,
    },
    groups,
    tracks: {},
    users: {},
  };

  return JSON.stringify(output, null, 2);
}
