import type { Rank, ServerType } from '../data';
import { getDefaultPermissionsForRank } from '../data';

interface GenerateOptions {
  serverType: ServerType;
  selectedPlugins: string[];
  ranks: Rank[];
}

export function generateYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  // Header comment
  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Plugins: ${selectedPlugins.join(', ')}`);
  lines.push('');
  lines.push('groups:');

  // Generate each rank
  for (const rank of ranks) {
    // Use rank.level to determine which permissions this rank should have
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    // Only include permissions that are specifically for this rank level
    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    lines.push(`  ${rank.name}:`);

    // Add inheritance (except for base rank)
    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    if (rankIndex > 0) {
      const parentRank = ranks[rankIndex - 1];
      lines.push('    inheritance:');
      lines.push(`      - ${parentRank.name}`);
    }

    // Add permissions
    if (rankSpecificPerms.length > 0) {
      lines.push('    permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`      - ${perm.node}`);
      }
    }

    // Add meta (prefix and separator)
    lines.push('    meta:');
    lines.push(`      prefix: '${rank.prefixColor}${rank.prefix}'`);
    if (rank.separator && rank.separator !== ':') {
      lines.push(`      separator: '${rank.separator}'`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  // Header
  lines.push('# ==========================================');
  lines.push('# PERMSTACK - LUCKPERMS SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  // Create groups
  lines.push('# Create groups (lowest to highest)');
  for (const rank of ranks) {
    lines.push(`/lp creategroup ${rank.name}`);
  }
  lines.push('');

  // Set inheritance
  lines.push('# Set inheritance chain');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/lp group ${rank.name} parent add ${parent.name}`);
  }
  lines.push('');

  // Add permissions for each rank
  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/lp group ${rank.name} permission set ${perm.node} true`);
      }
      lines.push('');
    }
  }

  // Set weights (higher rank = higher weight = higher priority)
  lines.push('# ---------- WEIGHTS ----------');
  const baseWeight = 79;
  for (let i = 0; i < ranks.length; i++) {
    const rank = ranks[i];
    const weight = baseWeight + i;
    lines.push(`/lp group ${rank.name} setweight ${weight}`);
  }
  lines.push('');

  // Set prefixes with weight priority
  lines.push('# ---------- PREFIXES ----------');
  for (let i = 0; i < ranks.length; i++) {
    const rank = ranks[i];
    const weight = baseWeight + i;
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/lp group ${rank.name} meta setprefix ${weight} "${prefix}"`);
  }
  lines.push('');

  // Set custom separators (if not default colon)
  const customSeparators = ranks.filter((r) => r.separator && r.separator !== ':');
  if (customSeparators.length > 0) {
    lines.push('# ---------- CHAT SEPARATORS ----------');
    lines.push('# Note: These require a chat plugin that supports custom separators');
    for (const rank of customSeparators) {
      lines.push(`/lp group ${rank.name} meta set separator "${rank.separator}"`);
    }
  }

  return lines.join('\n');
}

interface LuckPermsNode {
  type: 'permission' | 'inheritance' | 'prefix' | 'suffix' | 'weight' | 'meta' | 'display_name';
  key: string;
  value: boolean;
}

export function generateJson(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;

  const groups: Record<string, { nodes: LuckPermsNode[] }> = {};

  // Calculate base weight - higher ranks get higher weight
  const baseWeight = 79;

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    const parentRank = rankIndex > 0 ? ranks[rankIndex - 1] : null;
    const weight = baseWeight + rankIndex;

    const nodes: LuckPermsNode[] = [];

    // Add permission nodes
    for (const perm of rankSpecificPerms) {
      nodes.push({
        type: 'permission',
        key: perm.node,
        value: true,
      });
    }

    // Add inheritance (parent group)
    if (parentRank) {
      nodes.push({
        type: 'inheritance',
        key: `group.${parentRank.name}`,
        value: true,
      });
    }

    // Add prefix with weight
    const prefixValue = `${rank.prefixColor}${rank.prefix}`.trim();
    if (prefixValue) {
      nodes.push({
        type: 'prefix',
        key: `prefix.${weight}.${prefixValue}`,
        value: true,
      });
    }

    // Add weight
    nodes.push({
      type: 'weight',
      key: `weight.${weight}`,
      value: true,
    });

    // Add separator as meta if custom
    if (rank.separator && rank.separator !== ':') {
      nodes.push({
        type: 'meta',
        key: `meta.separator.${rank.separator}`,
        value: true,
      });
    }

    groups[rank.name] = {
      nodes,
    };
  }

  const output = {
    metadata: {
      generatedBy: 'PermStack',
      generatedAt: new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC',
    },
    groups,
    tracks: {},
    users: {},
  };

  return JSON.stringify(output, null, 2);
}
