import type { Rank, ServerType } from '../data';
import { getDefaultPermissionsForRank } from '../data';

interface GenerateOptions {
  serverType: ServerType;
  selectedPlugins: string[];
  ranks: Rank[];
}

export function generateYaml(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  // Header comment
  lines.push('# Generated by PermStack (permstack.io)');
  lines.push(`# Server Type: ${serverType}`);
  lines.push(`# Plugins: ${selectedPlugins.join(', ')}`);
  lines.push('');
  lines.push('groups:');

  // Generate each rank
  for (const rank of ranks) {
    // Use rank.level to determine which permissions this rank should have
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    // Only include permissions that are specifically for this rank level
    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    lines.push(`  ${rank.name}:`);

    // Add inheritance (except for base rank)
    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    if (rankIndex > 0) {
      const parentRank = ranks[rankIndex - 1];
      lines.push('    inheritance:');
      lines.push(`      - ${parentRank.name}`);
    }

    // Add permissions
    if (rankSpecificPerms.length > 0) {
      lines.push('    permissions:');
      for (const perm of rankSpecificPerms) {
        lines.push(`      - ${perm.node}`);
      }
    }

    // Add meta (prefix)
    lines.push('    meta:');
    lines.push(`      prefix: '${rank.prefixColor}${rank.prefix}'`);
    lines.push('');
  }

  return lines.join('\n');
}

export function generateCommands(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;
  const lines: string[] = [];

  // Header
  lines.push('# ==========================================');
  lines.push('# PERMSTACK - LUCKPERMS SETUP');
  lines.push('# https://permstack.io');
  lines.push('# ==========================================');
  lines.push('');

  // Create groups
  lines.push('# Create groups (lowest to highest)');
  for (const rank of ranks) {
    lines.push(`/lp creategroup ${rank.name}`);
  }
  lines.push('');

  // Set inheritance
  lines.push('# Set inheritance chain');
  for (let i = 1; i < ranks.length; i++) {
    const rank = ranks[i];
    const parent = ranks[i - 1];
    lines.push(`/lp group ${rank.name} parent add ${parent.name}`);
  }
  lines.push('');

  // Add permissions for each rank
  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    if (rankSpecificPerms.length > 0) {
      lines.push(`# ---------- ${rank.displayName.toUpperCase()} PERMISSIONS ----------`);
      for (const perm of rankSpecificPerms) {
        lines.push(`/lp group ${rank.name} permission set ${perm.node} true`);
      }
      lines.push('');
    }
  }

  // Set prefixes
  lines.push('# ---------- PREFIXES ----------');
  for (const rank of ranks) {
    const prefix = `${rank.prefixColor}${rank.prefix}`.replace(/"/g, '\\"');
    lines.push(`/lp group ${rank.name} meta setprefix "${prefix}"`);
  }

  return lines.join('\n');
}

export function generateJson(options: GenerateOptions): string {
  const { serverType, selectedPlugins, ranks } = options;

  const groups: Record<string, unknown> = {};

  for (const rank of ranks) {
    const permissions = getDefaultPermissionsForRank(
      rank.level,
      serverType,
      selectedPlugins
    );

    const rankSpecificPerms = permissions.filter(
      (p) => p.recommendedRank === rank.level
    );

    const rankIndex = ranks.findIndex((r) => r.id === rank.id);
    const parentRank = rankIndex > 0 ? ranks[rankIndex - 1] : null;

    const nodes: { key: string; value: boolean }[] = [];

    // Add permission nodes
    for (const perm of rankSpecificPerms) {
      nodes.push({
        key: perm.node,
        value: true,
      });
    }

    // Add parent
    if (parentRank) {
      nodes.push({
        key: `group.${parentRank.name}`,
        value: true,
      });
    }

    // Add prefix
    nodes.push({
      key: `prefix.${(rankIndex + 1) * 10}.${rank.prefixColor}${rank.prefix}`,
      value: true,
    });

    groups[rank.name] = {
      name: rank.name,
      nodes,
    };
  }

  const output = {
    '_schema-version': 1,
    groups,
  };

  return JSON.stringify(output, null, 2);
}
