import { useState, useEffect } from 'react';
import { ArrowRight, Copy, Check } from 'lucide-react';
import { Button } from './ui';

interface HeroProps {
  onStart: () => void;
}

// Simulated typing effect for the config preview
const configLines = [
  { text: '# Generated by PermStack', type: 'comment' },
  { text: '', type: 'blank' },
  { text: 'vip:', type: 'key' },
  { text: '  permissions:', type: 'subkey' },
  { text: '    - essentials.back', type: 'value' },
  { text: '    - essentials.sethome.multiple.3', type: 'value' },
  { text: '    - essentials.nick', type: 'value' },
  { text: '    - essentials.hat', type: 'value' },
  { text: '  parents:', type: 'subkey' },
  { text: '    - default', type: 'parent' },
  { text: '', type: 'blank' },
  { text: 'mvp:', type: 'key' },
  { text: '  permissions:', type: 'subkey' },
  { text: '    - essentials.fly', type: 'value' },
  { text: '    - essentials.feed', type: 'value' },
  { text: '    - essentials.workbench', type: 'value' },
  { text: '  parents:', type: 'subkey' },
  { text: '    - vip', type: 'parent' },
];

export function Hero({ onStart }: HeroProps) {
  const [visibleLines, setVisibleLines] = useState(0);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (visibleLines < configLines.length) {
      const timer = setTimeout(() => {
        setVisibleLines(v => v + 1);
      }, 120);
      return () => clearTimeout(timer);
    }
  }, [visibleLines]);

  const handleCopy = () => {
    const text = configLines.map(l => l.text).join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getLineColor = (type: string) => {
    switch (type) {
      case 'comment': return 'text-surface-500';
      case 'key': return 'text-purple-400';
      case 'subkey': return 'text-blue-400';
      case 'value': return 'text-green-400';
      case 'parent': return 'text-yellow-400';
      default: return 'text-surface-400';
    }
  };

  return (
    <div className="relative">
      {/* Subtle gradient background */}
      <div className="absolute inset-0 bg-gradient-to-b from-primary-500/5 via-transparent to-transparent" />

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-24">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: Copy + CTA */}
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-500/10 border border-primary-500/20 text-xs font-medium text-primary-400 mb-6">
              LuckPerms Configuration Generator
            </div>

            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white mb-4 leading-tight tracking-tight">
              Stop wrestling with<br />
              <span className="text-gradient">permission configs</span>
            </h1>

            <p className="text-surface-400 text-lg mb-8 max-w-md">
              Select your plugins, define your ranks, and export production-ready
              LuckPerms configurations in minutes.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 mb-10">
              <Button size="lg" onClick={onStart} className="inline-flex items-center gap-2">
                <span>Start Building</span>
                <ArrowRight className="w-5 h-5" />
              </Button>
            </div>

            {/* Trust indicators */}
            <div className="flex flex-wrap gap-6 text-sm text-surface-500">
              <div className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                <span>100+ plugins supported</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                <span>No account required</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                <span>Export in seconds</span>
              </div>
            </div>
          </div>

          {/* Right: Live Config Preview */}
          <div className="relative">
            <div className="bg-surface-900 border border-surface-800 rounded-xl overflow-hidden shadow-2xl shadow-black/20">
              {/* Window chrome */}
              <div className="flex items-center justify-between px-4 py-3 bg-surface-800/50 border-b border-surface-700">
                <div className="flex items-center gap-3">
                  <div className="flex gap-1.5">
                    <div className="w-3 h-3 rounded-full bg-surface-600" />
                    <div className="w-3 h-3 rounded-full bg-surface-600" />
                    <div className="w-3 h-3 rounded-full bg-surface-600" />
                  </div>
                  <span className="text-xs text-surface-500 font-mono">groups.yml</span>
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-2 py-1 text-xs text-surface-400 hover:text-white transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-green-400" />
                      <span className="text-green-400">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>

              {/* Code content */}
              <div className="p-4 font-mono text-sm leading-relaxed h-80 overflow-hidden">
                {configLines.slice(0, visibleLines).map((line, i) => (
                  <div key={i} className={`${getLineColor(line.type)} ${line.text === '' ? 'h-5' : ''}`}>
                    {line.text}
                  </div>
                ))}
                {visibleLines < configLines.length && (
                  <span className="inline-block w-2 h-4 bg-primary-500 animate-pulse" />
                )}
              </div>
            </div>

            {/* Floating badge */}
            <div className="absolute -bottom-4 -left-4 bg-surface-800 border border-surface-700 rounded-lg px-3 py-2 shadow-lg">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                <span className="text-xs text-surface-300">Live preview</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom section: How it works - compact */}
      <div className="border-t border-surface-800/50 bg-surface-900/30">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="text-center mb-10">
            <h2 className="text-xl font-semibold text-white">How it works</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-3xl mx-auto">
            {[
              { num: '1', title: 'Select plugins', desc: 'Choose from 100+ supported Minecraft plugins' },
              { num: '2', title: 'Define ranks', desc: 'Use templates or describe custom rank abilities' },
              { num: '3', title: 'Export config', desc: 'Download YAML, JSON, or copy commands' },
            ].map((step) => (
              <div key={step.num} className="text-center">
                <div className="w-8 h-8 rounded-full bg-surface-800 border border-surface-700 flex items-center justify-center text-sm font-medium text-surface-400 mx-auto mb-3">
                  {step.num}
                </div>
                <h3 className="text-sm font-medium text-white mb-1">{step.title}</h3>
                <p className="text-xs text-surface-500">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
